### ISSUE TITLE
Pypi tarball of version 0.2.0 doesn't include the LICENSE file

### ISSUE THREAD

**Issue by Moisan** [jurasofish/sphinx-toggleprompt#16]
The [pypi tarball](https://files.pythonhosted.org/packages/b2/83/6ecd7760c6bb7b599a76888e3fe7889f75a4453de2b24ea58753ef5ddd2d/sphinx-toggleprompt-0.2.0.tar.gz) doesn't include the LICENSE file. Would it be possible to add it in future releases?

**Comment by jurasofish** [comment]
sure
