### ISSUE TITLE
bug: Doesn't work for Sphinx==6.2.1

### ISSUE THREAD

**Issue by HHoofs** [jurasofish/sphinx-toggleprompt#23]
I upgraded Sphinx from version 5.~ to 6.2.1. in my project. The toggle-prompt key does no longer appear...

**Comment by jurasofish** [comment]
Cheers yeah looks like it isn't working with sphinx 6 at all on the default alabaster theme as jquery has been removed, I should probably have checked that a little more thoroughly.

Should be simple enough to sort out by thieving from https://github.com/python/python-docs-theme/pull/99

**Comment by Venkat-Rajgopal** [comment]
Using `6.1.3` with `pydata-theme` . Doesn't seem to work although the `sphinx_togglebutton` works.

**Comment by jurasofish** [comment]
aye I have a wip that works with sphinx 6 over at https://github.com/jurasofish/sphinx-toggleprompt/tree/sphinx_6.2.1

need to find time to polish it and get someone who Knows Something about web browsers etc to review it
